/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SRC;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import Databases.koneksiDatabases;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.view.JasperViewer; 
import Databases.koneksiDatabases; 
import java.awt.Dialog; 
import java.io.IOException;
import java.rmi.RemoteException; 
import java.sql.DriverManager;
import java.util.logging.Level; 
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader; 
import Databases.koneksiDatabases;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author LENOVO
 */
public class RekapData extends javax.swing.JFrame {

    /**
     * Creates new form RekapData
     */
    public RekapData() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btn_MenuUtama = new javax.swing.JLabel();
        Btn_Anggota = new javax.swing.JLabel();
        Btn_Pemasukkan = new javax.swing.JLabel();
        Btn_Pengeluaran = new javax.swing.JLabel();
        Btn_Rekap_Data = new javax.swing.JLabel();
        Btn_Exit = new javax.swing.JLabel();
        BtnPrintpengeluaran = new javax.swing.JLabel();
        Txtprint = new javax.swing.JTextField();
        BtnPrintpemasukkan = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Btn_MenuUtama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_MenuUtamaMouseClicked(evt);
            }
        });
        getContentPane().add(Btn_MenuUtama, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 280, 60));

        Btn_Anggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_AnggotaMouseClicked(evt);
            }
        });
        getContentPane().add(Btn_Anggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, 310, 60));

        Btn_Pemasukkan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_PemasukkanMouseClicked(evt);
            }
        });
        getContentPane().add(Btn_Pemasukkan, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 580, 310, 50));

        Btn_Pengeluaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_PengeluaranMouseClicked(evt);
            }
        });
        getContentPane().add(Btn_Pengeluaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 680, 310, 50));

        Btn_Rekap_Data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_Rekap_DataMouseClicked(evt);
            }
        });
        getContentPane().add(Btn_Rekap_Data, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 770, 280, 50));

        Btn_Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_ExitMouseClicked(evt);
            }
        });
        getContentPane().add(Btn_Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 910, 260, 70));

        BtnPrintpengeluaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnPrintpengeluaranMouseClicked(evt);
            }
        });
        getContentPane().add(BtnPrintpengeluaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 430, 200, 50));

        Txtprint.setBackground(new java.awt.Color(232, 229, 229));
        Txtprint.setBorder(null);
        getContentPane().add(Txtprint, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 310, 230, 30));

        BtnPrintpemasukkan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnPrintpemasukkanMouseClicked(evt);
            }
        });
        getContentPane().add(BtnPrintpemasukkan, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 420, 220, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/RekapData.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(1440, 1024));
        jLabel1.setMinimumSize(new java.awt.Dimension(1440, 1024));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 1040));

        setSize(new java.awt.Dimension(1440, 1024));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_MenuUtamaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_MenuUtamaMouseClicked
        // TODO add your handling code here: 
         new MenuUtama().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Btn_MenuUtamaMouseClicked

    private void Btn_AnggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_AnggotaMouseClicked
        // TODO add your handling code here: 
        new Anggota().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Btn_AnggotaMouseClicked

    private void Btn_PemasukkanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_PemasukkanMouseClicked
        // TODO add your handling code here: 
         new Pemasukkan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Btn_PemasukkanMouseClicked

    private void Btn_PengeluaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_PengeluaranMouseClicked
        // TODO add your handling code here: 
        new Pengeluaran().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Btn_PengeluaranMouseClicked

    private void Btn_Rekap_DataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_Rekap_DataMouseClicked
        // TODO add your handling code here:   
        new Pengeluaran().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Btn_Rekap_DataMouseClicked

    private void Btn_ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_ExitMouseClicked
        // TODO add your handling code here: 
        int ex = JOptionPane.showConfirmDialog(null, " Apakah anda akan keluar?", "Anda yakin?", JOptionPane.YES_NO_OPTION);
        if (ex == 0){
            dispose();
        }
        new Login().setVisible(true);
    }//GEN-LAST:event_Btn_ExitMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        for (double i = 0.0; i <=1.0;i = i + 0.1)
        {
            String val = i+ "";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try{
                Thread.sleep(40);
                
                
            }
            catch(Exception e)
            {
                
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void BtnPrintpengeluaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnPrintpengeluaranMouseClicked
        // TODO add your handling code here:  
        java.sql.Connection con = null;
        try {
            String jdbcDriver = "com.mysql.jdbc.Driver";
            Class.forName(jdbcDriver);

            String url = "jdbc:mysql://localhost:3306/siku1";
            String user = "root";
            String pass = "";

            con = DriverManager.getConnection(url, user, pass);
            Statement stm = con.createStatement();

            try {

                String report = ("C:\\Users\\ASUS\\Downloads\\siku\\src\\laporan\\Rekapitulasipengeluaran.jrxml"); 
                String relativePath=".\\siku\\src\\laporan\\Rekapitulasipengeluaran.jrxml";
                 HashMap hash = new HashMap();
                //Mengambil parameter dari ireport
                hash.put("kode", Txtprint.getText());
                JasperReport JRpt = JasperCompileManager.compileReport(report);
                JasperPrint JPrint = JasperFillManager.fillReport(JRpt, hash, con);
                JasperViewer.viewReport(JPrint, false);
            } catch (Exception rptexcpt) {
                System.out.println("Report Can't view because : " + rptexcpt);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_BtnPrintpengeluaranMouseClicked

    private void BtnPrintpemasukkanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnPrintpemasukkanMouseClicked
        // TODO add your handling code here: 
        java.sql.Connection con = null;
        try {
            String jdbcDriver = "com.mysql.jdbc.Driver";
            Class.forName(jdbcDriver);

            String url = "jdbc:mysql://localhost:3306/siku1";
            String user = "root";
            String pass = "";

            con = DriverManager.getConnection(url, user, pass);
            Statement stm = con.createStatement();

            try {

                String report = ("C:\\Users\\ASUS\\Downloads\\siku\\src\\laporan\\RekapitulasiPemasukkan.jrxml"); 
                String relativePath=".\\siku\\src\\laporan\\RekapitulasiPemasukkan.jrxml";
                 HashMap hash = new HashMap();
                //Mengambil parameter dari ireport
                hash.put("kode", Txtprint.getText());
                JasperReport JRpt = JasperCompileManager.compileReport(report);
                JasperPrint JPrint = JasperFillManager.fillReport(JRpt, hash, con);
                JasperViewer.viewReport(JPrint, false);
            } catch (Exception rptexcpt) {
                System.out.println("Report Can't view because : " + rptexcpt);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_BtnPrintpemasukkanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RekapData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RekapData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RekapData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RekapData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RekapData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BtnPrintpemasukkan;
    private javax.swing.JLabel BtnPrintpengeluaran;
    private javax.swing.JLabel Btn_Anggota;
    private javax.swing.JLabel Btn_Exit;
    private javax.swing.JLabel Btn_MenuUtama;
    private javax.swing.JLabel Btn_Pemasukkan;
    private javax.swing.JLabel Btn_Pengeluaran;
    private javax.swing.JLabel Btn_Rekap_Data;
    private javax.swing.JTextField Txtprint;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
